### PR TITLE
fix: rename matchPackageNames to matchDepNames as per renovate warning

### PR DESCRIPTION
**Pull request by mrjono1**
Will fix this warning

Repository problems

These problems occurred while renovating this repository. [View logs](https://developer.mend.io//github/SEEK-Jobs/bx-backends).

    WARN: Use matchDepNames instead of matchPackageNames

### CODE REVIEW

**Comment by AaronMoat** [comment]
Thanks @mrjono1! Do you know if there's a changelog somewhere? The documentation is not telling me whether or not they're equivalent (and doesn't mention the deprecation interestingly): https://docs.renovatebot.com/configuration-options/

**Comment by mrjono1** [comment]
Here is the Issue that shows the warning https://github.com/SEEK-Jobs/bx-backends/issues/3, ill see if I can find the change log as well

**Comment by AaronMoat** [comment]
@mrjono1 I am unsure if they're always replaced.

In one of my repos, it triggered for a buildkite matcher:

```
WARN: Use matchDepNames instead of matchPackageNames
{
  "packageRule": {
    "matchManagers": [
      "buildkite"
    ],
    "matchPackageNames": [
      "seek-jobs/gantry"
    ],
    "commitMessageAction": "",
    "commitMessageExtra": "{{newValue}}",
    "commitMessageTopic": "{{depName}}",
    "schedule": [
      "before 6:00 am every weekday"
    ]
  }
  "packageName": "seek-jobs/gantry-buildkite-plugin"
  "depName": "seek-jobs/gantry"
}
```

Can you check your debug logs and advise if it's similar? If so we could try just for that one first?

**Comment by mrjono1** [comment]
> @mrjono1 I am unsure if they're always replaced.
> 
> In one of my repos, it triggered for a buildkite matcher:
> 
> ```
> WARN: Use matchDepNames instead of matchPackageNames
> {
>   "packageRule": {
>     "matchManagers": [
>       "buildkite"
>     ],
>     "matchPackageNames": [
>       "seek-jobs/gantry"
>     ],
>     "commitMessageAction": "",
>     "commitMessageExtra": "{{newValue}}",
>     "commitMessageTopic": "{{depName}}",
>     "schedule": [
>       "before 6:00 am every weekday"
>     ]
>   }
>   "packageName": "seek-jobs/gantry-buildkite-plugin"
>   "depName": "seek-jobs/gantry"
> }
> ```
> 
> Can you check your debug logs and advise if it's similar? If so we could try just for that one first?

ahh ok ill have a look

**Comment by eepmoi** [comment]
@mrjono1 @AaronMoat - I was just about to raise a PR for the same fix then saw this one.  Are we able to revisit this?

I'm seeing the same issue, details here: https://github.com/SEEK-Jobs/releng-renovate-config/pull/14

> To fix this warning.
> https://developer.mend.io/github/SEEK-Jobs/releng-sample-app
> image
> 
> https://github.com/SEEK-Jobs/releng-sample-app/issues/6
> image
> 
> Docs: https://docs.renovatebot.com/configuration-options/#matchpackagenames
> image

Renovate logs:
```
WARN: Use matchDepNames instead of matchPackageNames
{
  "packageRule": {
    "matchManagers": [
      "buildkite"
    ],
    "matchPackageNames": [
      "seek-jobs/gantry"
    ],
    "schedule": [
      "after 3:00 am and before 5:00 pm every weekday"
    ],
    "minimumReleaseAge": "0 days",
    "updateNotScheduled": true
  }
  "packageName": "seek-jobs/gantry-buildkite-plugin"
  "depName": "seek-jobs/gantry"
}
```

**Comment by mrjono1** [comment]
I haven't had a chance to get back to this, I think I was over zealous with this change

**Review by samchungy — APPROVED** [review]
lgtm, if you can fix up the conflicts

**Comment by mrjono1** [comment]
@samchungy @eepmoi PR updated

**Review by 72636c — APPROVED** [review]

**Pull request merged**
